
#define INV_WEAPON_TABLE		0
//weapons
#define INV_SHOCKER					1
#define INV_STANDARD				2
#define INV_HANDGUN					3
#define INV_MICRO					4
#define INV_ROTSHOTGUN				5
#define INV_SUB						6
#define INV_A_RIFLE					7
#define INV_SNIPER					8
#define INV_PHOENIX					9
#define INV_TRIPACT					10
#define INV_GRENADE					11
#define INV_MINIGUN					12
#define INV_FLAME					13
#define INV_DBT						14
#define INV_RPG						15
#define INV_OMEGA					16
#define INV_THERMO					17
#define INV_FRAG_GREN				18
#define INV_FIRE_GREN				19

#define INV_AMMO_TABLE				30
#define INV_SHOCKER_AMMO			31
#define INV_STANDARD_AMMO			32
#define INV_HANDGUN_AMMO			33
#define INV_MICRO_AMMO				34
#define INV_ROTSHOTGUN_AMMO			35
#define INV_SUB_AMMO				36
#define INV_A_RIFLE_AMMO			37
#define INV_SNIPER_AMMO				38
#define INV_PHOENIX_AMMO			39
#define INV_TRIPACT_AMMO			40
#define INV_GRENADE_AMMO			41
#define INV_MINIGUN_AMMO			42
#define INV_FLAME_AMMO				43
#define INV_DBT_AMMO				44
#define INV_RPG_AMMO				45
#define INV_OMEGA_AMMO				46
#define INV_THERMO_AMMO				47
#define INV_FRAG_GREN_AMMO			48
#define INV_FIRE_GREN_AMMO			49

#define INV_CLIPAMMO_TABLE			60
#define INV_SHOCKER_CLIPAMMO		61
#define INV_STANDARD_CLIPAMMO		62
#define INV_HANDGUN_CLIPAMMO		63
#define INV_MICRO_CLIPAMMO			64
#define INV_ROTSHOTGUN_CLIPAMMO		65
#define INV_SUB_CLIPAMMO			66
#define INV_A_RIFLE_CLIPAMMO		67
#define INV_SNIPER_CLIPAMMO			68
#define INV_PHOENIX_CLIPAMMO		69
#define INV_TRIPACT_CLIPAMMO		70
#define INV_GRENADE_CLIPAMMO		71
#define INV_MINIGUN_CLIPAMMO		72
#define INV_FLAME_CLIPAMMO			73
#define INV_DBT_CLIPAMMO			74
#define INV_RPG_CLIPAMMO			75
#define INV_OMEGA_CLIPAMMO			76
#define INV_THERMO_CLIPAMMO			77
#define INV_FRAG_GREN_CLIPAMMO		78
#define INV_FIRE_GREN_CLIPAMMO		79

// inventory by category
#define INV_MELEE					100
#define INV_SIDEARM					101
#define INV_PRIMARY					102
#define INV_EXPLOSIVE				103
#define INV_SPECIAL					104

#define INV_MELEE_AMMO				110
#define INV_SIDEARM_AMMO			111
#define INV_PRIMARY_AMMO			112
#define INV_EXPLOSIVE_AMMO			113
#define INV_SPECIAL_AMMO			114

// other things
#define INV_GAMETYPE				120
#define INV_HEALTH					121
#define INV_ITEM					122

//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203

//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)

#define MODELINDEX_SHOCKER			1
#define MODELINDEX_STANDARD			2
#define MODELINDEX_HANDGUN			3
#define MODELINDEX_MICRO			4
#define MODELINDEX_ROTSHOTGUN		5
#define MODELINDEX_SUB				6
#define MODELINDEX_A_RIFLE			7
#define MODELINDEX_SNIPER			8
#define MODELINDEX_PHOENIX			9
#define MODELINDEX_TRIPACT			10
#define MODELINDEX_GRENADE			11
#define MODELINDEX_MINIGUN			12
#define MODELINDEX_FLAME			13
#define MODELINDEX_DBT				14
#define MODELINDEX_RPG				15
#define MODELINDEX_OMEGA			16
#define MODELINDEX_THERMO			17
#define MODELINDEX_FRAG_GREN		18
#define MODELINDEX_FIRE_GREN		19

// look at the table in bg_public.h
#define WEAPONINDEX_SHOCKER			1
#define WEAPONINDEX_STANDARD		2
#define WEAPONINDEX_HANDGUN			3
#define WEAPONINDEX_MICRO			4
#define WEAPONINDEX_ROTSHOTGUN		5
#define WEAPONINDEX_SUB				6
#define WEAPONINDEX_A_RIFLE			7
#define WEAPONINDEX_SNIPER			8
#define WEAPONINDEX_PHOENIX			9
#define WEAPONINDEX_TRIPACT			10
#define WEAPONINDEX_GRENADE			11
#define WEAPONINDEX_MINIGUN			12
#define WEAPONINDEX_FLAME			13
#define WEAPONINDEX_DBT				14
#define WEAPONINDEX_RPG				15
#define WEAPONINDEX_OMEGA			16
#define WEAPONINDEX_THERMO			17
#define WEAPONINDEX_FRAG_GREN		18
#define WEAPONINDEX_FIRE_GREN		19

